### ISSUE TITLE
Computer Requirements

### ISSUE THREAD

**Issue by JuantonioMS** [jtamames/SqueezeM#1]
Hello!
I'm working with gut metagenomics data and I would like to know...
How should the computer/server be? (for example: RAM, minimum CPU cores, free hard disk, etc.)
It is because I also know that programs like Centrifuge or Kraken uses a lot of RAM memory.
Thanks!!
PD: Could I use CentOs??

**Comment by fpusan** [comment]
Short answer is, it depends. Ideally, you'd like to have as much of both as you can. CPU cores will not be limiting per-se, but of course things will take longer with less powerful CPUs. Regarding RAM, the two memory limiting steps will be the assembly (specially for large datasets / coassembly) and alignment diamond.

We have actually managed to run the pipeline on the test data on a virtual machine with 24Gb of memory. In order to do that, we had to modify the 04.rundiamond.pl script so that the "-b" parameter in the nr diamond call (line 40) is set to 1 instead of 8.
We'll include the ability to control that parameter in the squeezeM.pl call in the next version.

So if you are short on RAM, I'd recommend doing that, and using either the "sequential" or the "merged" assembly modes.

Regarding CentOs, it _should_ work as long as you satisfy the dependencies. So the packages we list in the INSTALL file should have equivalents in CentOs, everything should work if they are installed.
A potential issue might be that some of the binaries were compiled in ubuntu with gcc5... depending on what version of gcc you have there might be some dynamic libraries missing too. In ubuntu it gets fixed by making sure that gcc-5 and its libraries are installed, hopefully it would work the same in CentOs.

Let us know if it works for you!
